### ISSUE TITLE
Funktioniert leider mit dem aktuellen Login nicht mehr

### ISSUE THREAD

**Issue by RolandE1204** [SmarthomeAddicted/Indego-Integration#1]
Leider funktioniert die Integration nicht mehr mit dem aktuellen Login (SingleKey)

**Comment by GerryCrooked** [comment]
SingleKey ID Login funktioniert aktuell nur über: https://github.com/sander1988/Indego mit Chrome Extention zum hinzufügen des Indegos.

**Comment by s3b0r** [comment]
> Would love to use this.
> 
> Do you plan to implement a fix @SmarthomeAddicted ?

@SmarthomeAddicted  That would be fantastic! Looking forward to use the updated version with the new Login and Map!

**Comment by SmarthomeAddicted** [comment]
please use the original one from jm-73 my Features from my forked version was added there and this version will be no longer supported
