### ISSUE TITLE
Erweiterung funktioniert mit aktuellen HA nicht

### ISSUE THREAD

**Issue by Kloenner** [SmarthomeAddicted/Indego-Integration#4]
Hallo, 
habe heute versucht Deine Erweiterung im Home Assistant zu laufen zu bringen, geht leider nicht, gibt es für den HA eine angepasste Version ?

Version vom HA
Core 2024.4.1
Supervisor 2024.03.1
Operating System 12.1
Frontend 20240404.1

MfG
Klönner

**Comment by mikburnz** [comment]
Bin auch sehr daran interessiert. Habe alle Schritte soweit befolgt. Beim Neustart kommt die Fehlermeldung: 
![image](https://github.com/SmarthomeAddicted/Indego-Integration/assets/154707156/27b2a2c2-44b3-4a3d-90e9-f0f5034ec243)

**Comment by SmarthomeAddicted** [comment]
please use the original one from jm-73 my Features from my forked version was added there and this version will be no longer supported
